spring:
  application:
    name: identity-provider-service

  datasource:
    url: jdbc:postgresql://192.168.29.72:5432/postgres
    username: @@@@@@@
    password: @@@@@@@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8888
